package org.uv.tpcs_practica04.GUI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.uv.tpcs_practica04.Cliente;
import org.uv.tpcs_practica04.DAOCliente;

/**
 *
 * @author francisco
 */
public class GUICliente extends javax.swing.JInternalFrame {
     /**
     * Creates new form EmpleadoGUI
     */
    public GUICliente() throws SQLException{
        initComponents();
        lista();
    }
    boolean bandera=false;
    String mensaje1="La clave ingresada no existe.";
    String mensaje2="El valor ingresado en el campo clave debe ser numerico";       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        panel_principal = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        EntradaId = new javax.swing.JTextField();
        entradaNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rfc = new javax.swing.JLabel();
        entradaRFC = new javax.swing.JTextField();
        bottonBuscar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Catalogo Clientes");
        setMinimumSize(new java.awt.Dimension(400, 300));

        jToolBar1.setRollover(true);

        jButton1.setText("nuevo");
        jButton1.setToolTipText("Nuevo Cliente");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("guardar");
        jButton2.setToolTipText("Guardar Cliente");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("modificar ");
        jButton3.setToolTipText("Modificar Cliente");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("eliminar");
        jButton4.setToolTipText("Eliminar Cliente");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator1);

        jButton5.setText("buscar ");
        jButton5.setToolTipText("Buscar Cliente");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        id.setText("ID:");

        nombre.setText("Nombre:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Direccion", "Telefonol"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        rfc.setText("RFC:");

        entradaRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaRFCActionPerformed(evt);
            }
        });

        bottonBuscar.setText("Buscar");
        bottonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addComponent(rfc)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(EntradaId, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottonBuscar))
                            .addComponent(entradaRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(EntradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rfc)
                    .addComponent(entradaRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_bottonBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Cliente emp;
            DAOCliente dao = new DAOCliente();
            long clave = Long.parseLong(EntradaId.getText());
            emp=dao.findByID(clave);
            if(emp!=null){
                int pase=JOptionPane.showConfirmDialog(this, "El Cliente "+clave+" sera actualizado...", "Mensaje de Confirmación", JOptionPane.YES_NO_OPTION);
                if(pase==0){
                    emp.setNombre(entradaNombre.getText());
                    emp.setRfc(entradaRFC.getText());
                    dao.update(emp, clave);
                    mensaje("Cliente modificado con exito!");
                    vaciarCampos();
                }
            }else{
                mensaje(mensaje1);
            }
        }catch(NumberFormatException ex){
           mensaje(mensaje2);
        }
        try {
            lista();
        } catch (SQLException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void lista() throws SQLException{
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("RFC");
        DAOCliente daoCliente=new DAOCliente();
        List<Cliente>listaEmpleados=daoCliente.findAll();
        for(Cliente cliente:listaEmpleados){
            model.addRow(new Object[]{String.valueOf(cliente.getClienteId()), cliente.getNombre(),cliente.getRfc()});
        }
        
        jTable1.setModel(model);

    }
    
    public void vaciarCampos(){
        EntradaId.setText("");
        entradaNombre.setText("");
        entradaRFC.setText("");
    }
    
    public void buscar(){
        try{
            long clave = Long.parseLong(EntradaId.getText());
            DAOCliente daoCliente=new DAOCliente();
            Cliente emp=daoCliente.findByID(clave);
            if(emp!=null){
                entradaNombre.setText(emp.getNombre());
                entradaRFC.setText(emp.getRfc());
            }else{
                mensaje(mensaje1);
            }
        }catch(NumberFormatException ex){
            mensaje(mensaje2);
        }
    }
    
    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            DAOCliente dao = new DAOCliente();
            long clave = Long.parseLong(EntradaId.getText());
            Cliente emp=dao.findByID(clave);
            if(emp!=null){
                int pase=JOptionPane.showConfirmDialog(this, "El cliente "+clave+" sera eliminado...", "Mensaje de Confirmación", JOptionPane.YES_NO_OPTION);
                if(pase==0){
                    dao.delete( clave);
                    mensaje("Cliente borrado con exito!");
                    vaciarCampos();
                }
            }else{
                mensaje(mensaje1);
            }
        }catch(NumberFormatException ex){
            mensaje(mensaje2);
        }
        try {
            lista();
        } catch (SQLException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(bandera){    
            try{
                Cliente emp;
                DAOCliente dao = new DAOCliente();
                String clave=EntradaId.getText();
                //emp=dao.findByID(clave);
                //if(emp==null){
                    emp=new Cliente();
                    //emp.setClienteId(clave);
                    emp.setNombre(entradaNombre.getText());
                    emp.setRfc(entradaRFC.getText());
                    dao.create(emp);
                    mensaje("Cliente registrado con exito!");
                    vaciarCampos();
                    bandera=false;
                    EntradaId.setEnabled(true);
                //}else{
                  //  mensaje("El Cliente con clave: "+clave+" ya existe.");
                //}
            }catch(NumberFormatException ex){
                mensaje(mensaje2);
            }
            try {
                lista();
            } catch (SQLException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            mensaje("Por favor, da click en nuevo");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(bandera==false){
            bandera=true;
            EntradaId.setEnabled(false);
            vaciarCampos();
        }else{
            bandera=false;
            EntradaId.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void entradaRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaRFCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EntradaId;
    private javax.swing.JButton bottonBuscar;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JTextField entradaRFC;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JLabel rfc;
    // End of variables declaration//GEN-END:variables
}
