package org.uv.tpcs_practica04.GUI;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.uv.tpcs_practica04.DAOProducto;
import org.uv.tpcs_practica04.Producto;

/**
 *
 * @author francisco
 */
public class GUIProducto extends javax.swing.JInternalFrame {
     /**
     * Creates new form EmpleadoGUI
     */
    public GUIProducto() throws SQLException{
        initComponents();
        lista();
    }
    boolean bandera=false;
    String mensaje1="La clave ingresada no existe.";
    String mensaje2="El valor ingresado en el campo clave debe ser numerico";       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        panel_principal = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        EntradaId = new javax.swing.JTextField();
        entradaDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        existencia = new javax.swing.JLabel();
        entradaExistencia = new javax.swing.JTextField();
        bottonBuscar = new javax.swing.JButton();
        precio = new javax.swing.JLabel();
        costo = new javax.swing.JLabel();
        entradaPrecio = new javax.swing.JTextField();
        entradaCosto = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Catalogo Productos");
        setMinimumSize(new java.awt.Dimension(400, 300));

        jToolBar1.setRollover(true);

        jButton1.setText("nuevo");
        jButton1.setToolTipText("Nuevo Producto");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("guardar");
        jButton2.setToolTipText("Guardar Producto");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText("modificar ");
        jButton3.setToolTipText("Modificar Producto");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText("eliminar");
        jButton4.setToolTipText("Eliminar Producto");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator1);

        jButton5.setText("buscar ");
        jButton5.setToolTipText("Buscar Producto");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        id.setText("ID:");

        descripcion.setText("Descripción:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Direccion", "Telefonol"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        existencia.setText("Existencia:");

        entradaExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaExistenciaActionPerformed(evt);
            }
        });

        bottonBuscar.setText("Buscar");
        bottonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBuscarActionPerformed(evt);
            }
        });

        precio.setText("Precio:");

        costo.setText("Costo:");

        entradaCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCostoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_principalLayout = new javax.swing.GroupLayout(panel_principal);
        panel_principal.setLayout(panel_principalLayout);
        panel_principalLayout.setHorizontalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_principalLayout.createSequentialGroup()
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcion)
                            .addComponent(existencia)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(entradaExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(costo)
                                .addGap(18, 18, 18)
                                .addComponent(entradaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(entradaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(precio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entradaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_principalLayout.createSequentialGroup()
                                .addComponent(EntradaId, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bottonBuscar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_principalLayout.setVerticalGroup(
            panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(EntradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion)
                    .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(entradaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precio)
                        .addComponent(entradaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(existencia)
                    .addGroup(panel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(entradaExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(costo)
                        .addComponent(entradaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_bottonBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Producto pro;
            DAOProducto dao = new DAOProducto();
            long clave = Long.parseLong(EntradaId.getText());
            pro=dao.findByID(clave);
            if(pro!=null){
                int pase=JOptionPane.showConfirmDialog(this, "El Producto "+clave+" sera actualizado...", "Mensaje de Confirmación", JOptionPane.YES_NO_OPTION);
                if(pase==0){
                    pro.setDescripcion(entradaDescripcion.getText());
                    pro.setExistencia(Integer.parseInt(entradaExistencia.getText()));
                    pro.setCosto(new BigDecimal(entradaCosto.getText()));
                    pro.setPrecio(new BigDecimal(entradaPrecio.getText()));
                    dao.update(pro, clave);
                    mensaje("Producto modificado con exito!");
                    vaciarCampos();
                }
            }else{
                mensaje(mensaje1);
            }
        }catch(NumberFormatException ex){
           mensaje(mensaje2);
        }
        try {
            lista();
        } catch (SQLException ex) {
            Logger.getLogger(GUIProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void lista() throws SQLException{
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Id");
        model.addColumn("Descripción");
        model.addColumn("Existencia");
        model.addColumn("Precio ($)");
        model.addColumn("Costo ($)");
        DAOProducto daoProducto=new DAOProducto();
        List<Producto>listaProductos=daoProducto.findAll();
        for(Producto pro:listaProductos){
            model.addRow(new Object[]{String.valueOf(pro.getProductoId()), pro.getDescripcion(),pro.getExistencia(), pro.getPrecio(), pro.getCosto()});
        }
        
        jTable1.setModel(model);

    }
    
    public void vaciarCampos(){
        EntradaId.setText("");
        entradaDescripcion.setText("");
        entradaExistencia.setText("");
        entradaPrecio.setText("");
        entradaCosto.setText("");
    }
    
    public void buscar(){
        try{
            long clave = Long.parseLong(EntradaId.getText());
            DAOProducto daoPro=new DAOProducto();
            Producto pro=daoPro.findByID(clave);
            if(pro!=null){
                entradaDescripcion.setText(pro.getDescripcion());
                entradaExistencia.setText(String.valueOf(pro.getExistencia()));
                entradaPrecio.setText(String.valueOf(pro.getPrecio()));
                entradaCosto.setText(String.valueOf(pro.getCosto()));
            }else{
                mensaje(mensaje1);
            }
        }catch(NumberFormatException ex){
            mensaje(mensaje2);
        }
    }
    
    public void mensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            DAOProducto dao = new DAOProducto();
            long clave = Long.parseLong(EntradaId.getText());
            Producto pro=dao.findByID(clave);
            if(pro!=null){
                int pase=JOptionPane.showConfirmDialog(this, "El Producto "+clave+" sera eliminado...", "Mensaje de Confirmación", JOptionPane.YES_NO_OPTION);
                if(pase==0){
                    dao.delete( clave);
                    mensaje("Producto borrado con exito!");
                    vaciarCampos();
                }
            }else{
                mensaje(mensaje1);
            }
        }catch(NumberFormatException ex){
            mensaje(mensaje2);
        }
        try {
            lista();
        } catch (SQLException ex) {
            Logger.getLogger(GUIProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(bandera){    
            try{
                Producto pro;
                DAOProducto dao = new DAOProducto();
                String clave=EntradaId.getText();
                //emp=dao.findByID(clave);
                //if(emp==null){
                    pro=new Producto();
                    //emp.setClienteId(clave);
                    pro.setDescripcion(entradaDescripcion.getText());
                    pro.setExistencia(Integer.parseInt(entradaExistencia.getText()));
                    pro.setPrecio(new  BigDecimal(entradaPrecio.getText()));
                    pro.setCosto(new  BigDecimal(entradaCosto.getText()));
                    dao.create(pro);
                    mensaje("Producto registrado con exito!");
                    vaciarCampos();
                    bandera=false;
                    EntradaId.setEnabled(true);
                //}else{
                  //  mensaje("El Cliente con clave: "+clave+" ya existe.");
                //}
            }catch(NumberFormatException ex){
                mensaje(mensaje2);
            }
            try {
                lista();
            } catch (SQLException ex) {
                Logger.getLogger(GUIProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            mensaje("Por favor, da click en nuevo");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(bandera==false){
            bandera=true;
            EntradaId.setEnabled(false);
            vaciarCampos();
        }else{
            bandera=false;
            EntradaId.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void entradaExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaExistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaExistenciaActionPerformed

    private void entradaCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaCostoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EntradaId;
    private javax.swing.JButton bottonBuscar;
    private javax.swing.JLabel costo;
    private javax.swing.JLabel descripcion;
    private javax.swing.JTextField entradaCosto;
    private javax.swing.JTextField entradaDescripcion;
    private javax.swing.JTextField entradaExistencia;
    private javax.swing.JTextField entradaPrecio;
    private javax.swing.JLabel existencia;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
}
